from pydantic import BaseModel, Field
from typing import List


class StudentAssessmentSummary(BaseModel):
    """Student context included in the assessment."""

    student_name: str
    degree: str
    branch: str
    current_year: int
    semester: int
    career_goal: str
    weekly_study_hours: float


class SkillGapResponse(BaseModel):
    """Structured representation of a student's skill gap."""

    skill_name: str
    current_level: float = Field(ge=0, le=100)
    target_level: float = Field(ge=0, le=100)
    gap: float = Field(ge=0, le=100)
    priority: str
    task: str
    resources: List[str] = Field(default_factory=list)
    timeline: str


class LearningRecommendation(BaseModel):
    """High-level learning recommendation."""

    description: str
    timeline: str


class LearningAssessmentResponse(BaseModel):
    """Complete structured assessment generated by the LLM."""

    summary: StudentAssessmentSummary
    skill_gaps: List[SkillGapResponse] = Field(default_factory=list)
    recommendations: List[LearningRecommendation] = Field(
        default_factory=list
    )