from pydantic import BaseModel, Field
from typing import List


class TutorResponse(BaseModel):
    """Structured response generated by the tutor agent."""

    topic: str
    explanation: str
    key_points: List[str] = Field(default_factory=list)
    example: str = ""
    practice_task: str = ""